apiVersion: serving.kubeflow.org/v1alpha2
kind: InferenceService
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  annotations:
    sidecar.istio.io/inject: "true"
  name: max-object-detector
  namespace: seldonp
spec:
  default:
    predictor:
      custom:
        container:
          name: max-object-detector
          image: k8scc01covidacr.azurecr.io/kfserving/max-object-detector:latest
          ports:
            - containerPort: 5000
              protocol: TCP
          resources:
            requests:
              cpu: "1"
              memory: "1024Mi"
            limits:
              cpu: "1"
              memory: "1024Mi"
      # serviceAccountName: azuresa